### PR TITLE
notify_observer with payload arguments

### PR DESCRIPTION
**Pull request by collin**
- with pluggable payload_coder; Marshal is default
- need to figure out what the sql injection danger is for pg

### CODE REVIEW

**Comment by collin** [comment]
In pg.rb it looks fairly straightforward to implement this, but I'm afraid of sql injection. What do we do? Or is my fear unjustified?

**Comment by tenderlove** [comment]
Is this going to work across processes?

WRT pg, we probably need to escape the channel and payload, but I don't think it's a huge thing to add.

**Comment by collin** [comment]
It appears to.

I'm using this locally to communicate between resque workers and a streaming controller (AC::Live)

Do you see anything specifically that concerns you?
Would it be a good idea to add some cross-process cases to the test?

**Comment by tenderlove** [comment]
Duhr.  Sorry, you're totally right, it would work cross process.  I was just misreading the diff.

I _suppose_ we should add tests that fork and make sure it works cross process.  But I'll merge this anyway.  Thanks! :D

**Pull request merged**
